BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "task" (
	"id"	INTEGER UNIQUE,
	"description"	TEXT NOT NULL,
	"long_session"	INTEGER NOT NULL DEFAULT 0,
	"tomato"	INTEGER NOT NULL DEFAULT 1,
	"done"	INTEGER NOT NULL DEFAULT 0,
	"progress"	INTEGER NOT NULL DEFAULT 0,
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "session" (
	"id"	INTEGER NOT NULL UNIQUE,
	"task"	INTEGER NOT NULL,
	"start"	INTEGER NOT NULL,
	"end"	INTEGER NOT NULL,
	"note"	TEXT,
	FOREIGN KEY("task") REFERENCES "task",
	PRIMARY KEY("id" AUTOINCREMENT)
);
CREATE INDEX IF NOT EXISTS "task_status" ON "task" (
	"done"
);
CREATE INDEX IF NOT EXISTS "session_task" ON "session" (
	"task"
);
COMMIT;
